### PR TITLE
Minecraft 1.8.3

### PR DESCRIPTION
**Pull request by Reginhar**
I updated the plugin and server libraries for Minecraft 1.8. This version works for Spigot and Bukkit 1.8.3. Can you update the plugin on the Bukkit website?

### CODE REVIEW

**Comment by EthanJoyce** [comment]
The project still doesn't compile correctly for me by simple performing:
`ant`

There are still some required libraries missing (e.g. http://mvnrepository.com/artifact/org.json/json).

**Comment by Reginhar** [comment]
Hmm, they should be in the bukkit jar... Can't find it

**Comment by EthanJoyce** [comment]
@Omniscimus They are included in the CraftBukkit JAR. Since we're only using the Bukkit API now, we'll need to include them ourselves.

**Comment by EthanJoyce** [comment]
Thanks for contributing!

**Pull request merged**
